export interface EmojiEntry {
  emoji: string
  name: string
}

export const emojiList: EmojiEntry[] = [
  // Smileys & Emotion
  { emoji: '😀', name: 'grinning face' },
  { emoji: '😁', name: 'beaming face with smiling eyes' },
  { emoji: '😂', name: 'face with tears of joy' },
  { emoji: '🤣', name: 'rolling on the floor laughing' },
  { emoji: '😃', name: 'grinning face with big eyes' },
  { emoji: '😄', name: 'grinning face with smiling eyes' },
  { emoji: '😅', name: 'grinning face with sweat' },
  { emoji: '😆', name: 'grinning squinting face' },
  { emoji: '😉', name: 'winking face' },
  { emoji: '😊', name: 'smiling face with smiling eyes' },
  { emoji: '😋', name: 'face savoring food' },
  { emoji: '😎', name: 'smiling face with sunglasses' },
  { emoji: '😍', name: 'smiling face with heart-eyes' },
  { emoji: '😘', name: 'face blowing a kiss' },
  { emoji: '🥰', name: 'smiling face with hearts' },
  { emoji: '😗', name: 'kissing face' },
  { emoji: '😙', name: 'kissing face with smiling eyes' },
  { emoji: '🥲', name: 'smiling face with tear' },
  { emoji: '😐', name: 'neutral face' },
  { emoji: '😑', name: 'expressionless face' },
  { emoji: '😶', name: 'face without mouth' },
  { emoji: '😏', name: 'smirking face' },
  { emoji: '😒', name: 'unamused face' },
  { emoji: '🙄', name: 'face with rolling eyes' },
  { emoji: '😬', name: 'grimacing face' },
  { emoji: '😔', name: 'pensive face' },
  { emoji: '😪', name: 'sleepy face' },
  { emoji: '🤤', name: 'drooling face' },
  { emoji: '😴', name: 'sleeping face' },
  { emoji: '😷', name: 'face with medical mask' },
  { emoji: '🤒', name: 'face with thermometer' },
  { emoji: '🤔', name: 'thinking face' },
  { emoji: '🤭', name: 'face with hand over mouth' },
  { emoji: '🤫', name: 'shushing face' },
  { emoji: '🤥', name: 'lying face' },
  { emoji: '😇', name: 'smiling face with halo' },
  { emoji: '🥳', name: 'partying face' },
  { emoji: '🥸', name: 'disguised face' },
  { emoji: '🤩', name: 'star-struck' },
  { emoji: '🥺', name: 'pleading face' },
  { emoji: '😢', name: 'crying face' },
  { emoji: '😭', name: 'loudly crying face' },
  { emoji: '😤', name: 'face with steam from nose' },
  { emoji: '😠', name: 'angry face' },
  { emoji: '😡', name: 'pouting face' },
  { emoji: '🤬', name: 'face with symbols on mouth' },
  { emoji: '😈', name: 'smiling face with horns' },
  { emoji: '👿', name: 'angry face with horns' },
  { emoji: '💀', name: 'skull' },
  { emoji: '☠️', name: 'skull and crossbones' },
  { emoji: '💩', name: 'pile of poo' },
  { emoji: '🤡', name: 'clown face' },
  { emoji: '👹', name: 'ogre' },
  { emoji: '👺', name: 'goblin' },
  { emoji: '👻', name: 'ghost' },
  { emoji: '👽', name: 'alien' },
  { emoji: '🤖', name: 'robot' },
  // Hand gestures
  { emoji: '👋', name: 'waving hand' },
  { emoji: '🤚', name: 'raised back of hand' },
  { emoji: '✋', name: 'raised hand' },
  { emoji: '🖖', name: 'vulcan salute' },
  { emoji: '👌', name: 'ok hand' },
  { emoji: '✌️', name: 'victory hand' },
  { emoji: '🤞', name: 'crossed fingers' },
  { emoji: '🤟', name: 'love-you gesture' },
  { emoji: '🤘', name: 'sign of the horns' },
  { emoji: '👈', name: 'backhand index pointing left' },
  { emoji: '👉', name: 'backhand index pointing right' },
  { emoji: '👆', name: 'backhand index pointing up' },
  { emoji: '👇', name: 'backhand index pointing down' },
  { emoji: '☝️', name: 'index pointing up' },
  { emoji: '👍', name: 'thumbs up' },
  { emoji: '👎', name: 'thumbs down' },
  { emoji: '✊', name: 'raised fist' },
  { emoji: '👊', name: 'oncoming fist' },
  { emoji: '🤛', name: 'left-facing fist' },
  { emoji: '🤜', name: 'right-facing fist' },
  { emoji: '👏', name: 'clapping hands' },
  { emoji: '🙌', name: 'raising hands' },
  { emoji: '👐', name: 'open hands' },
  { emoji: '🤲', name: 'palms up together' },
  { emoji: '🙏', name: 'folded hands' },
  { emoji: '✍️', name: 'writing hand' },
  { emoji: '💪', name: 'flexed biceps' },
  { emoji: '🦾', name: 'mechanical arm' },
  // Hearts & symbols
  { emoji: '❤️', name: 'red heart' },
  { emoji: '🧡', name: 'orange heart' },
  { emoji: '💛', name: 'yellow heart' },
  { emoji: '💚', name: 'green heart' },
  { emoji: '💙', name: 'blue heart' },
  { emoji: '💜', name: 'purple heart' },
  { emoji: '🖤', name: 'black heart' },
  { emoji: '🤍', name: 'white heart' },
  { emoji: '🤎', name: 'brown heart' },
  { emoji: '💔', name: 'broken heart' },
  { emoji: '💕', name: 'two hearts' },
  { emoji: '💞', name: 'revolving hearts' },
  { emoji: '💓', name: 'beating heart' },
  { emoji: '💗', name: 'growing heart' },
  { emoji: '💖', name: 'sparkling heart' },
  { emoji: '💘', name: 'heart with arrow' },
  { emoji: '💝', name: 'heart with ribbon' },
  { emoji: '⭐', name: 'star' },
  { emoji: '🌟', name: 'glowing star' },
  { emoji: '✨', name: 'sparkles' },
  { emoji: '💥', name: 'collision' },
  { emoji: '🔥', name: 'fire' },
  { emoji: '🎉', name: 'party popper' },
  { emoji: '🎊', name: 'confetti ball' },
  { emoji: '🎈', name: 'balloon' },
  { emoji: '🎁', name: 'wrapped gift' },
  { emoji: '🏆', name: 'trophy' },
  { emoji: '🥇', name: 'first place medal' },
  { emoji: '🎯', name: 'bullseye' },
  { emoji: '🎮', name: 'video game' },
  // Nature
  { emoji: '🌈', name: 'rainbow' },
  { emoji: '☀️', name: 'sun' },
  { emoji: '🌤️', name: 'sun behind small cloud' },
  { emoji: '⛅', name: 'sun behind cloud' },
  { emoji: '🌥️', name: 'sun behind large cloud' },
  { emoji: '☁️', name: 'cloud' },
  { emoji: '🌦️', name: 'sun behind rain cloud' },
  { emoji: '🌧️', name: 'cloud with rain' },
  { emoji: '⛈️', name: 'cloud with lightning and rain' },
  { emoji: '🌩️', name: 'cloud with lightning' },
  { emoji: '🌨️', name: 'cloud with snow' },
  { emoji: '❄️', name: 'snowflake' },
  { emoji: '🌊', name: 'water wave' },
  { emoji: '🌸', name: 'cherry blossom' },
  { emoji: '🌺', name: 'hibiscus' },
  { emoji: '🌻', name: 'sunflower' },
  { emoji: '🌹', name: 'rose' },
  { emoji: '🍀', name: 'four leaf clover' },
  { emoji: '🌿', name: 'herb' },
  { emoji: '🍃', name: 'leaf fluttering in wind' },
  { emoji: '🐶', name: 'dog face' },
  { emoji: '🐱', name: 'cat face' },
  { emoji: '🐭', name: 'mouse face' },
  { emoji: '🐹', name: 'hamster' },
  { emoji: '🐰', name: 'rabbit face' },
  { emoji: '🦊', name: 'fox' },
  { emoji: '🐻', name: 'bear' },
  { emoji: '🐼', name: 'panda' },
  { emoji: '🐨', name: 'koala' },
  { emoji: '🐯', name: 'tiger face' },
  { emoji: '🦁', name: 'lion' },
  { emoji: '🐸', name: 'frog' },
  { emoji: '🐵', name: 'monkey face' },
  { emoji: '🐔', name: 'chicken' },
  { emoji: '🐧', name: 'penguin' },
  { emoji: '🐦', name: 'bird' },
  { emoji: '🦋', name: 'butterfly' },
  // Food
  { emoji: '🍕', name: 'pizza' },
  { emoji: '🍔', name: 'hamburger' },
  { emoji: '🍟', name: 'french fries' },
  { emoji: '🌮', name: 'taco' },
  { emoji: '🍜', name: 'steaming bowl' },
  { emoji: '🍣', name: 'sushi' },
  { emoji: '🍱', name: 'bento box' },
  { emoji: '🍩', name: 'doughnut' },
  { emoji: '🍪', name: 'cookie' },
  { emoji: '🎂', name: 'birthday cake' },
  { emoji: '🍰', name: 'shortcake' },
  { emoji: '🧁', name: 'cupcake' },
  { emoji: '🍫', name: 'chocolate bar' },
  { emoji: '🍬', name: 'candy' },
  { emoji: '☕', name: 'hot beverage' },
  { emoji: '🧋', name: 'bubble tea' },
  { emoji: '🍺', name: 'beer mug' },
  { emoji: '🥂', name: 'clinking glasses' },
  // Objects & Misc
  { emoji: '📱', name: 'mobile phone' },
  { emoji: '💻', name: 'laptop' },
  { emoji: '🖥️', name: 'desktop computer' },
  { emoji: '⌨️', name: 'keyboard' },
  { emoji: '🖨️', name: 'printer' },
  { emoji: '📷', name: 'camera' },
  { emoji: '📸', name: 'camera with flash' },
  { emoji: '📺', name: 'television' },
  { emoji: '📻', name: 'radio' },
  { emoji: '🔋', name: 'battery' },
  { emoji: '💡', name: 'light bulb' },
  { emoji: '🔦', name: 'flashlight' },
  { emoji: '📚', name: 'books' },
  { emoji: '📖', name: 'open book' },
  { emoji: '📝', name: 'memo' },
  { emoji: '✏️', name: 'pencil' },
  { emoji: '🖊️', name: 'pen' },
  { emoji: '📌', name: 'pushpin' },
  { emoji: '📎', name: 'paperclip' },
  { emoji: '✂️', name: 'scissors' },
  { emoji: '🗑️', name: 'wastebasket' },
  { emoji: '🔒', name: 'locked' },
  { emoji: '🔓', name: 'unlocked' },
  { emoji: '🔑', name: 'key' },
  { emoji: '🔨', name: 'hammer' },
  { emoji: '⚙️', name: 'gear' },
  { emoji: '🔧', name: 'wrench' },
  { emoji: '🧲', name: 'magnet' },
  { emoji: '💣', name: 'bomb' },
  { emoji: '🛡️', name: 'shield' },
  { emoji: '⚔️', name: 'crossed swords' },
  { emoji: '🚀', name: 'rocket' },
  { emoji: '✈️', name: 'airplane' },
  { emoji: '🚗', name: 'automobile' },
  { emoji: '🚕', name: 'taxi' },
  { emoji: '🚌', name: 'bus' },
  { emoji: '🚂', name: 'locomotive' },
  { emoji: '⛵', name: 'sailboat' },
  { emoji: '🏠', name: 'house' },
  { emoji: '🏢', name: 'office building' },
  { emoji: '🌍', name: 'globe showing europe-africa' },
  { emoji: '🌎', name: 'globe showing americas' },
  { emoji: '🌏', name: 'globe showing asia-australia' },
  { emoji: '🗺️', name: 'world map' },
  { emoji: '🏔️', name: 'snow-capped mountain' },
  { emoji: '⛰️', name: 'mountain' },
  { emoji: '🏖️', name: 'beach with umbrella' },
  { emoji: '🏕️', name: 'camping' },
  // Symbols
  { emoji: '✅', name: 'check mark button' },
  { emoji: '❌', name: 'cross mark' },
  { emoji: '❓', name: 'question mark' },
  { emoji: '❗', name: 'exclamation mark' },
  { emoji: '💯', name: 'hundred points' },
  { emoji: '🔴', name: 'red circle' },
  { emoji: '🟠', name: 'orange circle' },
  { emoji: '🟡', name: 'yellow circle' },
  { emoji: '🟢', name: 'green circle' },
  { emoji: '🔵', name: 'blue circle' },
  { emoji: '🟣', name: 'purple circle' },
  { emoji: '⚫', name: 'black circle' },
  { emoji: '⚪', name: 'white circle' },
  { emoji: '🔶', name: 'large orange diamond' },
  { emoji: '🔷', name: 'large blue diamond' },
  { emoji: '🔸', name: 'small orange diamond' },
  { emoji: '🔹', name: 'small blue diamond' },
  { emoji: '▶️', name: 'play button' },
  { emoji: '⏸️', name: 'pause button' },
  { emoji: '⏹️', name: 'stop button' },
  { emoji: '⏺️', name: 'record button' },
  { emoji: '🔀', name: 'shuffle tracks button' },
  { emoji: '🔁', name: 'repeat button' },
  { emoji: '🔔', name: 'bell' },
  { emoji: '🔕', name: 'bell with slash' },
  { emoji: '📢', name: 'loudspeaker' },
  { emoji: '📣', name: 'megaphone' },
  { emoji: '🔇', name: 'muted speaker' },
  { emoji: '🔈', name: 'speaker low volume' },
  { emoji: '🔉', name: 'speaker medium volume' },
  { emoji: '🔊', name: 'speaker high volume' },
  { emoji: '⬆️', name: 'up arrow' },
  { emoji: '⬇️', name: 'down arrow' },
  { emoji: '⬅️', name: 'left arrow' },
  { emoji: '➡️', name: 'right arrow' },
  { emoji: '↩️', name: 'right arrow curving left' },
  { emoji: '↪️', name: 'left arrow curving right' },
  { emoji: '🔃', name: 'clockwise vertical arrows' },
  { emoji: '🔄', name: 'counterclockwise arrows button' },
  { emoji: 'ℹ️', name: 'information' },
  { emoji: '⚠️', name: 'warning' },
  { emoji: '🚫', name: 'prohibited' },
  { emoji: '🆕', name: 'new button' },
  { emoji: '🆙', name: 'up button' },
  { emoji: '🆒', name: 'cool button' },
  { emoji: '🆓', name: 'free button' },
  { emoji: '🆗', name: 'ok button' },
  { emoji: '🆘', name: 'sos button' },
]

